import { createClient, SupabaseClient } from '@supabase/supabase-js';
import { GeneratedContent, DatabaseItem } from '../types';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_KEY;
/*
  REQUIRED DATABASE SCHEMA (Supabase SQL):
  
  create table generated_content (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    topic text,
    data jsonb
  );

  -- Don't forget to enable RLS and add policies for anon access if needed.
  -- Example Policy for Insert:
  -- create policy "Enable insert for all users" on "public"."generated_content" as PERMISSIVE for INSERT to anon with check (true);
*/

// Safely initialize Supabase client
let supabase: SupabaseClient | null = null;

if (supabaseUrl && supabaseKey) {
  try {
    supabase = createClient(supabaseUrl, supabaseKey);
  } catch (error) {
    console.error("Supabase initialization failed:", error);
  }
}

export const saveContent = async (topic: string, content: GeneratedContent): Promise<any> => {
  if (!supabase) {
    throw new Error("Supabase is not configured. Please add SUPABASE_URL and SUPABASE_KEY to your environment.");
  }

  const { data, error } = await supabase
    .from('generated_content')
    .insert([
      { topic: topic, data: content }
    ])
    .select();

  if (error) {
    console.error("Supabase Save Error:", JSON.stringify(error, null, 2));
    throw new Error(error.message || "Database insert failed");
  }
  return data;
};

export const getSavedContents = async (): Promise<DatabaseItem[]> => {
  if (!supabase) {
    throw new Error("Supabase is not configured.");
  }

  const { data, error } = await supabase
    .from('generated_content')
    .select('*')
    .order('created_at', { ascending: false });

  if (error) {
    console.error("Supabase Fetch Error:", JSON.stringify(error, null, 2));
    throw new Error(error.message || "Failed to fetch history");
  }
  
  return data as DatabaseItem[];
};